version: '2'
volumes:
  node-red-data:
  config:
  influx-data:
networks:
  node-red-net:
services:
  homeassistant:
    build: homeassistant
    ports:
      - 80:8123
    privileged: true
    volumes:
      - 'config:/config'
    restart: always
    devices:
      - '/dev:/dev'
      - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
  mqtt:
    build:
      context: .
      dockerfile: ./mosquitto/Dockerfile
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    image: arm32v6/eclipse-mosquitto
    ports:
      - '1883:1883'
    restart: always
  hass-configurator:
    image: 'causticlab/hass-configurator-docker:arm'
    restart: always
    ports:
      - '8080:3218'
    volumes:
      - 'config:/hass-config'
    environment:
      - HC_BASEPATH=/hass-config
  node-red:
    build: ./node-red
    restart: always
    privileged: true
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
    cap_add:
      - SYS_RAWIO
    devices:
      - '/dev/mem:/dev/mem'
      - '/dev/gpiomem:/dev/gpiomem'
      - '/dev/i2c-1:/dev/i2c-1'
    ports:
      - 8888:80
    volumes:
      - 'node-red-data:/data'
  influxdb:
    restart: always
    image: arm32v7/influxdb
    volumes:
      - 'influx-data:/var/lib/influxdb'
