version: '2'
volumes:
  node-red-data:
  config:
networks:
  node-red-net:
services:
  homeassistant:
    build: homeassistant
    ports:
      - 8123:8123
    privileged: true
    volumes:
      - 'config:/config'
    restart: always
    devices:
      - '/dev:/dev'
      - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
  mqtt:
    image: arm32v6/eclipse-mosquitto
    ports:
      - '1883:1883'
    restart: always
  hass-configurator:
    image: 'causticlab/hass-configurator-docker:arm'
    restart: always
    ports:
      - '8080:3218'
    volumes:
      - 'config:/hass-config'
    environment:
      - HC_BASEPATH=/hass-config
  node-red:
    build: ./node-red
    restart: always
    privileged: true
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
    cap_add:
      - SYS_RAWIO
    devices:
      - '/dev/mem:/dev/mem'
      - '/dev/gpiomem:/dev/gpiomem'
      - '/dev/i2c-1:/dev/i2c-1'
    ports:
      - 8888:80
    volumes:
      - 'node-red-data:/data'
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '80:80/tcp'
      - '443:443/tcp'
    labels:
      io.balena.features.supervisor-api: '1'
    environment:
      TZ: 'Europe/London'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
